# Generated by Django 2.0.7 on 2018-07-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_auto_20180730_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
