//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashingEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rainbow
    {
        public decimal id { get; set; }
        public string password { get; set; }
        public string md5hash { get; set; }
        public string sha1hash { get; set; }
        public string sha2hash { get; set; }
    }
}
