//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkRainbow2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RainbowEntities : DbContext
    {
        public RainbowEntities()
            : base("name=RainbowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bulk> Bulks { get; set; }
        public virtual DbSet<Pass> Passes { get; set; }
        public virtual DbSet<BulksPassword> BulksPasswords { get; set; }
    }
}
