//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkRainbow2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pass
    {
        public int ID { get; set; }
        public string Pass1 { get; set; }
        public string MD5 { get; set; }
        public string SHA1 { get; set; }
        public string SHA2 { get; set; }
    }
}
