//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hash_RevHash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hash
    {
        public int ID { get; set; }
        public string Password { get; set; }
        public string Md5Hash { get; set; }
        public string Sha2Hash { get; set; }
        public string Sha1Hash { get; set; }
    }
}
