# Generated by Django 2.0.7 on 2018-07-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0002_auto_20180728_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
