# Generated by Django 2.0.7 on 2018-08-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0006_auto_20180730_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_image'),
        ),
    ]
