# Generated by Django 2.0.7 on 2018-07-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_auto_20180730_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='nr_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='nr_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='text',
            name='nr_likes',
            field=models.IntegerField(default=0),
        ),
    ]
