# Generated by Django 2.0.7 on 2018-07-31 09:11

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0008_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='link',
            name='created_date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='text',
            name='created_date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
