# Generated by Django 2.0.7 on 2018-08-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeReddit', '0003_auto_20180801_1520'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'user')},
        ),
    ]
