# Generated by Django 2.0.7 on 2018-08-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeReddit', '0004_auto_20180802_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='No Title', max_length=150),
        ),
    ]
